contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - curl
    - bash
    - busybox
    - ca-certificates-bundle
    - wolfi-baselayout
    - kube-bench

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 65532

entrypoint:
  command: kube-bench

archs:
- x86_64
- aarch64
